# This file is similar to a .env file or configuration dictionary in Flask.
# Here we define application-level configurations.

# Start the built-in Tomcat server on port 8080 (the default for Spring Boot)
server.port=8080
